package jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-06-03T19:41:32.576+03:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://helloworld.jaxws/", name = "Hello")
@XmlSeeAlso({ObjectFactory.class})
public interface Hello {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://helloworld.jaxws/", className = "jaxws.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://helloworld.jaxws/", className = "jaxws.client.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
